const CHART_COLORS = ['#ff5555', '#55ff55', '#5555ff', '#ffff55', '#ff55ff', '#55ffff', '#ffaa55', '#aa55ff', '#ff8888', '#88ff88', '#8888ff', '#ffff88', '#ff88ff', '#88ffff', '#ffcc88', '#cc88ff'];

const SECTOR_COLORS = {
    semi: '#33ff33', electronics: '#5555ff', software_ai: '#00ffff', game: '#ff5555', telecom: '#aaaaaa', auto: '#ffff55', finance: '#ff55ff', realestate: '#55ffff', retail: '#ffaa55', food: '#aaffaa', pharma: '#ffaaaa', transport: '#55aaff', energy: '#ff8800'
};

const MEALS = {
    'skip': { cost: 0, satiety: -20, health: -5, happiness: -10, stress: 5 },
    'cheap': { cost: 300, satiety: 30, health: -1, happiness: 0, stress: 2 },
    'normal': { cost: 600, satiety: 60, health: 1, happiness: 2, stress: -2 },
    'luxury': { cost: 3000, satiety: 100, health: 2, happiness: 10, stress: -10 }
};

const DIFFICULTIES = {
    'easy': { name: '🟢 寬鬆環境 (Easy)', initDebt: 0, taxRate: 0.05, feeRate: 0.002, loanMult: 0.5, baseDailyCost: 500, stressMult: 0.5, divMult: 1.5, marketDriftMod: 0.003, badEventProb: 0.1 },
    'normal': { name: '🟡 常規市場 (Normal)', initDebt: 0, taxRate: 0.15, feeRate: 0.005, loanMult: 1.0, baseDailyCost: 500, stressMult: 1.0, divMult: 1.0, marketDriftMod: 0.000, badEventProb: 0.3 },
    'hard': { name: '🟠 嚴苛監管 (Hard)', initDebt: 0, taxRate: 0.25, feeRate: 0.01, loanMult: 1.5, baseDailyCost: 500, stressMult: 1.5, divMult: 0.5, marketDriftMod: -0.002, badEventProb: 0.6 },
    'hell': { name: '🔴 地獄開局 (Hell)', initDebt: 5000000, taxRate: 0.40, feeRate: 0.02, loanMult: 2.0, baseDailyCost: 500, stressMult: 2.0, divMult: 0.2, marketDriftMod: -0.004, badEventProb: 0.8 }
};

let DB = {
    sectors: {
        semi: { name: '半導體與設備', baseVol: 0.05, trendRate: 0.0006, rateSensitivity: -0.8, links: { electronics: 0.5, software_ai: 0.4, auto: 0.2, energy: -0.3 } },
        electronics: { name: '電腦與週邊', baseVol: 0.04, trendRate: 0.0004, rateSensitivity: -0.5, links: { software_ai: 0.3, telecom: 0.3 } },
        software_ai: { name: '軟體與網路', baseVol: 0.06, trendRate: 0.0007, rateSensitivity: -1.0, links: { electronics: 0.3, telecom: 0.2 } },
        game: { name: '遊戲與文創', baseVol: 0.06, trendRate: 0.0005, rateSensitivity: -0.4, links: { software_ai: 0.3 } },
        telecom: { name: '通信與網路', baseVol: 0.02, trendRate: 0.0002, rateSensitivity: -0.2, links: { software_ai: 0.2 } },
        auto: { name: '汽車與重工', baseVol: 0.03, trendRate: 0.0002, rateSensitivity: -0.6, links: { transport: 0.3, energy: -0.4 } },
        finance: { name: '金融與保險', baseVol: 0.025, trendRate: 0.0003, rateSensitivity: 1.2, links: { realestate: 0.5 } },
        realestate: { name: '建材與營造', baseVol: 0.035, trendRate: 0.0004, rateSensitivity: -1.5, links: { finance: 0.4 } },
        retail: { name: '百貨與零售', baseVol: 0.02, trendRate: 0.0001, rateSensitivity: -0.2, links: { food: 0.4 } },
        food: { name: '食品與農業', baseVol: 0.015, trendRate: 0.0001, rateSensitivity: -0.1, links: { retail: 0.3 } },
        pharma: { name: '生技與醫療', baseVol: 0.055, trendRate: 0.0004, rateSensitivity: -0.3, links: {} },
        transport: { name: '航運與物流', baseVol: 0.05, trendRate: 0.0003, rateSensitivity: -0.4, links: { energy: -0.6, retail: 0.2 } },
        energy: { name: '塑膠與能源', baseVol: 0.04, trendRate: 0.0002, rateSensitivity: -0.2, links: { transport: -0.5, auto: -0.3, semi: -0.2 } }
    },
    unlistedPool: [
        { id: '2330', name: '台積電', sector: 'semi', bizModel: 'foundry', basePrice: 4500, beta: 1.2, divYield: 0.02, liquidity: 500000 },
        { id: '2303', name: '聯電', sector: 'semi', bizModel: 'foundry', basePrice: 1500, beta: 1.3, divYield: 0.04, liquidity: 300000 },
        { id: '2454', name: '聯發科', sector: 'semi', bizModel: 'design', basePrice: 6500, beta: 1.5, divYield: 0.05, liquidity: 150000 },
        { id: '2388', name: '威盛', sector: 'semi', bizModel: 'design', basePrice: 1200, beta: 2.2, divYield: 0.0, liquidity: 150000 },
        { id: '3443', name: '創意', sector: 'semi', bizModel: 'design', basePrice: 8500, beta: 1.8, divYield: 0.02, liquidity: 50000 },
        { id: '3661', name: '世芯-KY', sector: 'semi', bizModel: 'design', basePrice: 12000, beta: 1.9, divYield: 0.01, liquidity: 30000 },
        { id: '3227', name: '原相', sector: 'semi', bizModel: 'design', basePrice: 2200, beta: 1.5, divYield: 0.03, liquidity: 80000 },
        { id: '2379', name: '瑞昱', sector: 'semi', bizModel: 'design', basePrice: 3500, beta: 1.4, divYield: 0.04, liquidity: 100000 },
        { id: '3711', name: '日月光投控', sector: 'semi', bizModel: 'equipment', basePrice: 2200, beta: 1.1, divYield: 0.03, liquidity: 250000 },
        { id: '6488', name: '環球晶', sector: 'semi', bizModel: 'equipment', basePrice: 4800, beta: 1.6, divYield: 0.02, liquidity: 80000 },
        { id: '2337', name: '旺宏', sector: 'semi', bizModel: 'idm', basePrice: 800, beta: 1.8, divYield: 0.02, liquidity: 200000 },
        { id: '2408', name: '南亞科', sector: 'semi', bizModel: 'idm', basePrice: 1200, beta: 1.7, divYield: 0.01, liquidity: 180000 },
        { id: '6770', name: '力積電', sector: 'semi', bizModel: 'foundry', basePrice: 600, beta: 1.5, divYield: 0.0, liquidity: 220000 },
        { id: '5347', name: '世界', sector: 'semi', bizModel: 'foundry', basePrice: 1800, beta: 1.2, divYield: 0.03, liquidity: 120000 },
        { id: '2311', name: '日月光', sector: 'semi', bizModel: 'equipment', basePrice: 1500, beta: 1.1, divYield: 0.04, liquidity: 150000 },
        { id: '3037', name: '欣興', sector: 'semi', bizModel: 'equipment', basePrice: 2500, beta: 1.6, divYield: 0.03, liquidity: 120000 },
        { id: '3583', name: '辛耘', sector: 'semi', bizModel: 'equipment', basePrice: 2000, beta: 1.4, divYield: 0.02, liquidity: 50000 },
        { id: '3131', name: '弘塑', sector: 'semi', bizModel: 'equipment', basePrice: 4500, beta: 1.5, divYield: 0.02, liquidity: 25000 },
        { id: '6187', name: '萬潤', sector: 'semi', bizModel: 'equipment', basePrice: 1500, beta: 1.4, divYield: 0.03, liquidity: 35000 },
        { id: '2404', name: '漢唐', sector: 'semi', bizModel: 'equipment', basePrice: 2500, beta: 1.0, divYield: 0.05, liquidity: 40000 },
        { id: 'ASML', name: 'ASML (艾司摩爾)', sector: 'semi', bizModel: 'equipment', basePrice: 18000, beta: 1.3, divYield: 0.01, liquidity: 400000 },
        { id: 'NVDA', name: 'NVIDIA (輝達)', sector: 'semi', bizModel: 'design', basePrice: 25000, beta: 2.2, divYield: 0.005, liquidity: 800000 },
        { id: 'INTC', name: 'Intel (英特爾)', sector: 'semi', bizModel: 'idm', basePrice: 5500, beta: 0.9, divYield: 0.03, liquidity: 600000 },
        { id: 'AMD', name: 'AMD (超微)', sector: 'semi', bizModel: 'design', basePrice: 8500, beta: 1.9, divYield: 0.0, liquidity: 500000 },
        { id: 'QCOM', name: 'Qualcomm (高通)', sector: 'semi', bizModel: 'design', basePrice: 9500, beta: 1.4, divYield: 0.02, liquidity: 350000 },
        { id: 'AVGO', name: 'Broadcom (博通)', sector: 'semi', bizModel: 'design', basePrice: 12000, beta: 1.3, divYield: 0.025, liquidity: 300000 },
        { id: 'TXN', name: 'Texas Instruments', sector: 'semi', bizModel: 'idm', basePrice: 8000, beta: 1.0, divYield: 0.03, liquidity: 250000 },
        { id: 'ARM', name: 'ARM (安謀)', sector: 'semi', bizModel: 'design', basePrice: 6500, beta: 1.6, divYield: 0.0, liquidity: 450000 },
        { id: '8035', name: 'Tokyo Electron', sector: 'semi', bizModel: 'equipment', basePrice: 14000, beta: 1.4, divYield: 0.01, liquidity: 200000 },
        { id: 'AMAT', name: 'Applied Materials', sector: 'semi', bizModel: 'equipment', basePrice: 9000, beta: 1.4, divYield: 0.01, liquidity: 250000 },
        { id: 'LRCX', name: 'Lam Research', sector: 'semi', bizModel: 'equipment', basePrice: 11000, beta: 1.5, divYield: 0.01, liquidity: 200000 },
        { id: 'MU', name: 'Micron (美光)', sector: 'semi', bizModel: 'idm', basePrice: 7500, beta: 1.7, divYield: 0.01, liquidity: 400000 },
        { id: '2317', name: '鴻海', sector: 'electronics', bizModel: 'ems', productType: 'consumer_ems', customProduct: 'iPhone 旗艦智慧手機與家用遊戲機精密組裝', basePrice: 1800, beta: 1.1, divYield: 0.04, liquidity: 600000 },
        { id: '2498', name: '宏達電', sector: 'electronics', bizModel: 'brand', productType: 'console', customProduct: 'VIVE 高階 VR 虛擬實境頭戴裝置', basePrice: 600, beta: 2.5, divYield: 0.0, liquidity: 200000 },
        { id: '2382', name: '廣達', sector: 'electronics', bizModel: 'ems', productType: 'pc_ems', customProduct: '雲端巨頭高階 AI 伺服器與 MacBook 筆電代工', basePrice: 2100, beta: 1.4, divYield: 0.03, liquidity: 200000 },
        { id: '3231', name: '緯創', sector: 'electronics', bizModel: 'ems', productType: 'pc_ems', customProduct: '企業商務 PC 與高頻寬網路伺服器主板組裝', basePrice: 1200, beta: 1.6, divYield: 0.03, liquidity: 250000 },
        { id: '6669', name: '緯穎', sector: 'electronics', bizModel: 'server_ipc', productType: 'ai_server', customProduct: '超大型雲端資料中心客製化液冷 AI 伺服器機櫃', basePrice: 15000, beta: 1.8, divYield: 0.02, liquidity: 50000 },
        { id: '2357', name: '華碩', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'ROG 玩家共和國高階電競筆電與板卡', basePrice: 3200, beta: 1.0, divYield: 0.05, liquidity: 100000 },
        { id: '2353', name: '宏碁', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'TravelMate 輕薄商務筆電與 Chromebook', basePrice: 500, beta: 1.3, divYield: 0.04, liquidity: 150000 },
        { id: '2376', name: '技嘉', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'AORUS 高階電競電腦與超頻顯示卡', basePrice: 2500, beta: 1.7, divYield: 0.03, liquidity: 120000 },
        { id: '2377', name: '微星', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'MSI 專業電競筆電與電競周邊配件', basePrice: 1800, beta: 1.5, divYield: 0.04, liquidity: 100000 },
        { id: '2395', name: '研華', sector: 'electronics', bizModel: 'server_ipc', productType: 'industrial_pc', customProduct: '智慧工廠物聯網邊緣運算控制器與工控主板', basePrice: 3800, beta: 0.8, divYield: 0.03, liquidity: 60000 },
        { id: '2324', name: '仁寶', sector: 'electronics', bizModel: 'ems', productType: 'pc_ems', customProduct: '品牌廠 Chromebook 與常規筆電大批量組裝', basePrice: 600, beta: 0.9, divYield: 0.05, liquidity: 200000 },
        { id: '2356', name: '英業達', sector: 'electronics', bizModel: 'ems', productType: 'pc_ems', customProduct: '品牌筆電與資料中心伺服器機架組裝', basePrice: 700, beta: 1.2, divYield: 0.04, liquidity: 180000 },
        { id: '4938', name: '和碩', sector: 'electronics', bizModel: 'ems', productType: 'consumer_ems', customProduct: '智慧終端裝置、遊戲機與穿戴式裝置組裝', basePrice: 850, beta: 1.0, divYield: 0.05, liquidity: 150000 },
        { id: '2308', name: '台達電', sector: 'electronics', bizModel: 'components', productType: 'power_unit', customProduct: 'AI 伺服器專用大功率電源與浸沒式散熱模組', basePrice: 3200, beta: 0.9, divYield: 0.03, liquidity: 180000 },
        { id: '2301', name: '光寶科', sector: 'electronics', bizModel: 'components', productType: 'power_unit', customProduct: '高階雲端伺服器鈦金級電源與光電組件', basePrice: 1200, beta: 1.0, divYield: 0.05, liquidity: 160000 },
        { id: '2352', name: '佳世達', sector: 'electronics', bizModel: 'ems', productType: 'automotive_ems', customProduct: '車載中控電腦、醫療高規顯示器代工', basePrice: 800, beta: 1.1, divYield: 0.04, liquidity: 150000 },
        { id: '3008', name: '大立光', sector: 'electronics', bizModel: 'components', productType: 'optics', customProduct: '潛望式超高階八片式 (8P) 手機光學鏡頭組', basePrice: 22000, beta: 1.2, divYield: 0.02, liquidity: 20000 },
        { id: '2327', name: '國巨', sector: 'electronics', bizModel: 'components', productType: 'passives', customProduct: '全球車規與高頻寬 MLCC 被動積層陶瓷電容', basePrice: 5500, beta: 1.5, divYield: 0.02, liquidity: 80000 },
        { id: '2354', name: '鴻準', sector: 'electronics', bizModel: 'components', productType: 'passives', customProduct: '智慧手機精密輕量化金屬機殼與遊戲機散熱機構', basePrice: 900, beta: 1.3, divYield: 0.03, liquidity: 140000 },
        { id: '2367', name: '華通', sector: 'electronics', bizModel: 'components', productType: 'passives', customProduct: '低軌衛星專用高階 HDI 印刷電路板', basePrice: 750, beta: 1.4, divYield: 0.04, liquidity: 150000 },
        { id: '3044', name: '健鼎', sector: 'electronics', bizModel: 'components', productType: 'passives', customProduct: '車載電子與高階記憶體模組專用印刷電路板', basePrice: 1800, beta: 1.1, divYield: 0.05, liquidity: 80000 },
        { id: '4958', name: '臻鼎-KY', sector: 'electronics', bizModel: 'components', productType: 'passives', customProduct: '手機主板與折疊智慧裝置專用超薄軟性電路板', basePrice: 1100, beta: 1.3, divYield: 0.04, liquidity: 70000 },
        { id: 'AAPL', name: 'Apple (蘋果)', sector: 'electronics', bizModel: 'brand', productType: 'handheld', customProduct: 'iPhone 智慧手機與 iOS 封閉生態系', basePrice: 18000, beta: 1.1, divYield: 0.01, liquidity: 900000 },
        { id: '6758', name: 'Sony (索尼)', sector: 'electronics', bizModel: 'brand', productType: 'console', customProduct: 'PlayStation 次世代家用遊戲主機', basePrice: 4200, beta: 1.2, divYield: 0.015, liquidity: 300000 },
        { id: '005930', name: 'Samsung (三星)', sector: 'electronics', bizModel: 'brand', productType: 'handheld', customProduct: 'Galaxy 折疊手機與消費性全品類電子產品', basePrice: 8000, beta: 1.3, divYield: 0.02, liquidity: 400000 },
        { id: 'DELL', name: 'Dell (戴爾)', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'Latitude 企業商務 PC 與 XPS 頂級筆電', basePrice: 5000, beta: 1.2, divYield: 0.02, liquidity: 200000 },
        { id: 'HPQ', name: 'HP (惠普)', sector: 'electronics', bizModel: 'brand', productType: 'pc_laptop', customProduct: 'EliteBook 企業辦公 PC 與 Pavilion 家用筆電', basePrice: 3000, beta: 1.0, divYield: 0.03, liquidity: 200000 },
        { id: 'CSCO', name: 'Cisco (思科)', sector: 'electronics', bizModel: 'server_ipc', productType: 'industrial_pc', customProduct: '企業級骨幹路由器與邊緣運算防火牆整合機架', basePrice: 4800, beta: 0.9, divYield: 0.03, liquidity: 350000 },
        { id: 'SMCI', name: 'Super Micro', sector: 'electronics', bizModel: 'server_ipc', productType: 'ai_server', customProduct: '超高密度 NVIDIA HGX H100 GPU 散熱伺服器集群', basePrice: 8500, beta: 2.5, divYield: 0.0, liquidity: 150000 },
        { id: '2345', name: '智邦', sector: 'software_ai', bizModel: 'si_services', basePrice: 4500, beta: 1.3, divYield: 0.03, liquidity: 60000 },
        { id: '5203', name: '訊連', sector: 'software_ai', bizModel: 'subscription', basePrice: 900, beta: 1.2, divYield: 0.03, liquidity: 30000 },
        { id: '8044', name: '網家', sector: 'software_ai', bizModel: 'ads_platform', basePrice: 500, beta: 1.8, divYield: 0.0, liquidity: 40000 },
        { id: '8454', name: '富邦媒', sector: 'software_ai', bizModel: 'ads_platform', basePrice: 4500, beta: 1.4, divYield: 0.02, liquidity: 30000 },
        { id: '8069', name: '零壹', sector: 'software_ai', bizModel: 'si_services', basePrice: 700, beta: 1.1, divYield: 0.05, liquidity: 25000 },
        { id: '2480', name: '敦陽科', sector: 'software_ai', bizModel: 'si_services', basePrice: 1200, beta: 0.9, divYield: 0.06, liquidity: 20000 },
        { id: '6214', name: '精誠', sector: 'software_ai', bizModel: 'si_services', basePrice: 1100, beta: 0.8, divYield: 0.05, liquidity: 25000 },
        { id: '6153', name: '邁達特', sector: 'software_ai', bizModel: 'si_services', basePrice: 650, beta: 1.0, divYield: 0.06, liquidity: 30000 },
        { id: '3022', name: '威強電', sector: 'software_ai', bizModel: 'si_services', basePrice: 800, beta: 1.2, divYield: 0.04, liquidity: 40000 },
        { id: 'MSFT', name: 'Microsoft (微軟)', sector: 'software_ai', bizModel: 'subscription', basePrice: 28000, beta: 1.1, divYield: 0.01, liquidity: 850000 },
        { id: 'GOOGL', name: 'Google (谷歌)', sector: 'software_ai', bizModel: 'ads_platform', basePrice: 26000, beta: 1.2, divYield: 0.0, liquidity: 800000 },
        { id: 'META', name: 'Meta (臉書)', sector: 'software_ai', bizModel: 'ads_platform', basePrice: 19000, beta: 1.6, divYield: 0.0, liquidity: 700000 },
        { id: 'AMZN', name: 'Amazon (亞馬遜)', sector: 'software_ai', bizModel: 'ads_platform', basePrice: 22000, beta: 1.4, divYield: 0.0, liquidity: 750000 },
        { id: 'OAI', name: 'OpenAI (概念)', sector: 'software_ai', bizModel: 'ai_model', basePrice: 35000, beta: 2.5, divYield: 0.0, liquidity: 600000 },
        { id: 'PLTR', name: 'Palantir', sector: 'software_ai', bizModel: 'ai_model', basePrice: 2000, beta: 2.2, divYield: 0.0, liquidity: 400000 },
        { id: 'ADBE', name: 'Adobe (奧多比)', sector: 'software_ai', bizModel: 'subscription', basePrice: 15000, beta: 1.3, divYield: 0.0, liquidity: 250000 },
        { id: 'CRM', name: 'Salesforce', sector: 'software_ai', bizModel: 'subscription', basePrice: 11000, beta: 1.4, divYield: 0.0, liquidity: 250000 },
        { id: 'ORCL', name: 'Oracle (甲骨文)', sector: 'software_ai', bizModel: 'subscription', basePrice: 8500, beta: 1.0, divYield: 0.02, liquidity: 300000 },
        { id: 'NFLX', name: 'Netflix (網飛)', sector: 'software_ai', bizModel: 'subscription', basePrice: 14000, beta: 1.7, divYield: 0.0, liquidity: 400000 },
        { id: 'SNOW', name: 'Snowflake', sector: 'software_ai', bizModel: 'ai_model', basePrice: 4500, beta: 2.0, divYield: 0.0, liquidity: 180000 },
        { id: 'CRWD', name: 'CrowdStrike', sector: 'software_ai', bizModel: 'subscription', basePrice: 6500, beta: 1.9, divYield: 0.0, liquidity: 200000 },
        { id: '3293', name: '鈊象', sector: 'game', bizModel: 'live_ops', basePrice: 8500, beta: 1.3, divYield: 0.05, liquidity: 40000 },
        { id: '6180', name: '橘子', sector: 'game', bizModel: 'live_ops', basePrice: 850, beta: 1.5, divYield: 0.06, liquidity: 50000 },
        { id: '5478', name: '智冠', sector: 'game', bizModel: 'platform', basePrice: 1200, beta: 1.2, divYield: 0.05, liquidity: 45000 },
        { id: '3083', name: '網龍', sector: 'game', bizModel: 'live_ops', basePrice: 400, beta: 1.8, divYield: 0.0, liquidity: 30000 },
        { id: '3546', name: '宇峻', sector: 'game', bizModel: 'live_ops', basePrice: 750, beta: 1.4, divYield: 0.04, liquidity: 20000 },
        { id: '3086', name: '華義', sector: 'game', bizModel: 'live_ops', basePrice: 600, beta: 2.0, divYield: 0.0, liquidity: 15000 },
        { id: '3687', name: '歐買尬', sector: 'game', bizModel: 'live_ops', basePrice: 450, beta: 1.9, divYield: 0.0, liquidity: 20000 },
        { id: '7974', name: 'Nintendo (任天堂)', sector: 'game', bizModel: 'ip_franchise', basePrice: 4500, beta: 1.1, divYield: 0.02, liquidity: 350000 },
        { id: 'EA', name: 'EA (美商藝電)', sector: 'game', bizModel: 'aaa_studio', basePrice: 6500, beta: 1.2, divYield: 0.01, liquidity: 200000 },
        { id: 'TTWO', name: 'Take-Two', sector: 'game', bizModel: 'aaa_studio', basePrice: 7000, beta: 1.4, divYield: 0.0, liquidity: 150000 },
        { id: 'UBI', name: 'Ubisoft', sector: 'game', bizModel: 'aaa_studio', basePrice: 1500, beta: 1.6, divYield: 0.0, liquidity: 100000 },
        { id: '0700', name: 'Tencent (騰訊)', sector: 'game', bizModel: 'live_ops', basePrice: 12000, beta: 1.5, divYield: 0.01, liquidity: 500000 },
        { id: 'NTES', name: 'NetEase (網易)', sector: 'game', bizModel: 'live_ops', basePrice: 8000, beta: 1.4, divYield: 0.01, liquidity: 250000 },
        { id: 'RBLX', name: 'Roblox', sector: 'game', bizModel: 'platform', basePrice: 1200, beta: 2.1, divYield: 0.0, liquidity: 180000 },
        { id: 'DIS', name: 'Disney (迪士尼)', sector: 'game', bizModel: 'ip_franchise', basePrice: 8500, beta: 1.0, divYield: 0.015, liquidity: 450000 },
        { id: '2412', name: '中華電', sector: 'telecom', bizModel: 'mno', basePrice: 1200, beta: 0.4, divYield: 0.05, liquidity: 300000 },
        { id: '3045', name: '台灣大', sector: 'telecom', bizModel: 'mno', basePrice: 1000, beta: 0.5, divYield: 0.05, liquidity: 150000 },
        { id: '4904', name: '遠傳', sector: 'telecom', bizModel: 'mno', basePrice: 850, beta: 0.5, divYield: 0.05, liquidity: 150000 },
        { id: 'T', name: 'AT&T', sector: 'telecom', bizModel: 'mno', basePrice: 800, beta: 0.6, divYield: 0.07, liquidity: 500000 },
        { id: 'VZ', name: 'Verizon', sector: 'telecom', bizModel: 'mno', basePrice: 1500, beta: 0.5, divYield: 0.06, liquidity: 400000 },
        { id: 'TMUS', name: 'T-Mobile', sector: 'telecom', bizModel: 'mno', basePrice: 4500, beta: 0.8, divYield: 0.01, liquidity: 300000 },
        { id: '9432', name: 'NTT', sector: 'telecom', bizModel: 'idc_cloud', basePrice: 500, beta: 0.5, divYield: 0.04, liquidity: 400000 },
        { id: '9984', name: 'SoftBank (軟銀)', sector: 'telecom', bizModel: 'tech_holding', basePrice: 3500, beta: 1.6, divYield: 0.02, liquidity: 350000 },
        { id: '2207', name: '和泰車', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'Toyota Altis 國民車 / Lexus RX 豪華 SUV / Town Ace 輕卡', basePrice: 7500, beta: 0.8, divYield: 0.04, liquidity: 80000 },
        { id: '2201', name: '裕隆', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'Luxgen n7 純電 SUV / Nissan 乘用車代工裝配線', basePrice: 650, beta: 1.2, divYield: 0.02, liquidity: 100000 },
        { id: '2204', name: '中華車', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'CMC Veryca / Delica 輕型商用車與 MG 國產 SUV', basePrice: 800, beta: 0.9, divYield: 0.05, liquidity: 60000 },
        { id: '2206', name: '三陽工業', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'SYM 運動速克達 (DRG) 與 Hyundai 國產代工乘用車', basePrice: 750, beta: 1.4, divYield: 0.03, liquidity: 120000 },
        { id: '9921', name: '巨大 (捷安特)', sector: 'auto', bizModel: 'specialty_heavy', customProduct: 'GIANT TCR 頂規公路賽車與高端 E-Bike 電子輔助自行車', basePrice: 2200, beta: 1.0, divYield: 0.03, liquidity: 50000 },
        { id: '9914', name: '美利達', sector: 'auto', bizModel: 'specialty_heavy', customProduct: 'MERIDA REACTO 銳克多跑車與越野避震登山自行車', basePrice: 1800, beta: 1.1, divYield: 0.04, liquidity: 40000 },
        { id: '6605', name: '帝寶', sector: 'auto', bizModel: 'tier1_am', customProduct: '全球 AM 市場高階副廠專利 LED 頭燈與導光防霧尾燈模具', basePrice: 1500, beta: 1.1, divYield: 0.04, liquidity: 30000 },
        { id: '1536', name: '和大', sector: 'auto', bizModel: 'tier1_am', customProduct: 'Tesla 高精密減速齒輪箱與 BorgWarner 傳動軸差速組件', basePrice: 700, beta: 1.5, divYield: 0.02, liquidity: 45000 },
        { id: '2231', name: '為升', sector: 'auto', bizModel: 'tier1_am', customProduct: '77/79GHz 毫米波雷達盲點偵測與 TPMS 胎壓電子晶片', basePrice: 1200, beta: 1.6, divYield: 0.03, liquidity: 25000 },
        { id: '2634', name: '漢翔', sector: 'auto', bizModel: 'specialty_heavy', customProduct: 'T-5 勇鷹高級教練機與 GE 航空引擎精密發動機段件', basePrice: 550, beta: 0.9, divYield: 0.04, liquidity: 80000 },
        { id: 'TSLA', name: 'Tesla (特斯拉)', sector: 'auto', bizModel: 'ev_innovator', customProduct: 'Model 3/Y 一體壓鑄平民款與 Cybertruck 不鏽鋼皮卡', basePrice: 18000, beta: 2.5, divYield: 0.0, liquidity: 900000 },
        { id: '7203', name: 'Toyota (豐田)', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'Corolla / RAV4 / Prius 全球混動神車家族與 Lexus 旗艦豪華車', basePrice: 5500, beta: 0.9, divYield: 0.03, liquidity: 500000 },
        { id: 'HMC', name: 'Honda (本田)', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'CR-V 經典運動休旅、Civic 房車與傳奇 Super Cub 二輪機車', basePrice: 1200, beta: 1.0, divYield: 0.04, liquidity: 200000 },
        { id: 'F', name: 'Ford (福特)', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'F-150 美式硬派皮卡、Mustang 野馬跑車與 Focus 國產轎車', basePrice: 400, beta: 1.4, divYield: 0.05, liquidity: 300000 },
        { id: 'GM', name: 'GM (通用)', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'Cadillac Escalade 旗艦休旅與 Hummer EV 越野重卡', basePrice: 1500, beta: 1.3, divYield: 0.01, liquidity: 250000 },
        { id: 'BMW', name: 'BMW', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'BMW 3/5/7 系列豪華房車與 M Power 全系列高性能轎跑車', basePrice: 3800, beta: 1.2, divYield: 0.06, liquidity: 150000 },
        { id: 'VOW3', name: 'Volkswagen (福斯)', sector: 'auto', bizModel: 'legacy_oem', customProduct: 'VW Golf / Tiguan 國民房車與 ID.4 全球平價純電 SUV 系列', basePrice: 4200, beta: 1.3, divYield: 0.07, liquidity: 180000 },
        { id: 'RACE', name: 'Ferrari (法拉利)', sector: 'auto', bizModel: 'specialty_heavy', customProduct: 'SF90 / LaFerrari 傳奇限量 V12 超級跑車與 Purosangue 跑旅', basePrice: 12000, beta: 1.1, divYield: 0.01, liquidity: 100000 },
        { id: '1211', name: 'BYD (比亞迪)', sector: 'auto', bizModel: 'ev_innovator', customProduct: '秦/宋 DM-i 超級混動車與仰望 U8 水陸兩棲 SUV / 刀片電池', basePrice: 8500, beta: 1.8, divYield: 0.01, liquidity: 400000 },
        { id: '2881', name: '富邦金', sector: 'finance', bizModel: 'insurance', basePrice: 700, beta: 1.2, divYield: 0.05, liquidity: 400000 },
        { id: '2882', name: '國泰金', sector: 'finance', bizModel: 'insurance', basePrice: 600, beta: 1.1, divYield: 0.05, liquidity: 350000 },
        { id: '2891', name: '中信金', sector: 'finance', bizModel: 'payment', basePrice: 350, beta: 1.0, divYield: 0.06, liquidity: 500000 },
        { id: '2886', name: '兆豐金', sector: 'finance', bizModel: 'commercial', basePrice: 400, beta: 0.8, divYield: 0.05, liquidity: 300000 },
        { id: '2884', name: '玉山金', sector: 'finance', bizModel: 'commercial', basePrice: 280, beta: 0.9, divYield: 0.06, liquidity: 350000 },
        { id: '2885', name: '元大金', sector: 'finance', bizModel: 'investment', basePrice: 320, beta: 1.3, divYield: 0.05, liquidity: 250000 },
        { id: '2892', name: '第一金', sector: 'finance', bizModel: 'commercial', basePrice: 270, beta: 0.7, divYield: 0.05, liquidity: 200000 },
        { id: '2880', name: '華南金', sector: 'finance', bizModel: 'commercial', basePrice: 250, beta: 0.7, divYield: 0.05, liquidity: 180000 },
        { id: '5880', name: '合庫金', sector: 'finance', bizModel: 'commercial', basePrice: 260, beta: 0.6, divYield: 0.05, liquidity: 150000 },
        { id: '2887', name: '台新金', sector: 'finance', bizModel: 'payment', basePrice: 200, beta: 1.1, divYield: 0.06, liquidity: 250000 },
        { id: '2883', name: '開發金', sector: 'finance', bizModel: 'investment', basePrice: 150, beta: 1.4, divYield: 0.06, liquidity: 450000 },
        { id: '2888', name: '新光金', sector: 'finance', bizModel: 'insurance', basePrice: 100, beta: 1.5, divYield: 0.03, liquidity: 500000 },
        { id: '2890', name: '永豐金', sector: 'finance', bizModel: 'commercial', basePrice: 220, beta: 1.0, divYield: 0.05, liquidity: 200000 },
        { id: '2801', name: '彰銀', sector: 'finance', bizModel: 'commercial', basePrice: 180, beta: 0.7, divYield: 0.05, liquidity: 120000 },
        { id: '2834', name: '臺企銀', sector: 'finance', bizModel: 'commercial', basePrice: 160, beta: 0.8, divYield: 0.05, liquidity: 150000 },
        { id: '2845', name: '遠東銀', sector: 'finance', bizModel: 'commercial', basePrice: 140, beta: 0.8, divYield: 0.05, liquidity: 100000 },
        { id: '2838', name: '聯邦銀', sector: 'finance', bizModel: 'commercial', basePrice: 150, beta: 0.7, divYield: 0.05, liquidity: 80000 },
        { id: '5871', name: '中租-KY', sector: 'finance', bizModel: 'payment', basePrice: 1800, beta: 1.5, divYield: 0.04, liquidity: 80000 },
        { id: 'JPM', name: 'JPMorgan (摩根大通)', sector: 'finance', bizModel: 'commercial', basePrice: 6500, beta: 1.1, divYield: 0.02, liquidity: 500000 },
        { id: 'GS', name: 'Goldman Sachs (高盛)', sector: 'finance', bizModel: 'investment', basePrice: 12000, beta: 1.3, divYield: 0.01, liquidity: 200000 },
        { id: 'MS', name: 'Morgan Stanley', sector: 'finance', bizModel: 'investment', basePrice: 3200, beta: 1.4, divYield: 0.02, liquidity: 250000 },
        { id: 'BAC', name: 'Bank of America', sector: 'finance', bizModel: 'commercial', basePrice: 1200, beta: 1.2, divYield: 0.03, liquidity: 600000 },
        { id: 'C', name: 'Citigroup (花旗)', sector: 'finance', bizModel: 'commercial', basePrice: 1800, beta: 1.3, divYield: 0.04, liquidity: 450000 },
        { id: 'WFC', name: 'Wells Fargo', sector: 'finance', bizModel: 'commercial', basePrice: 1600, beta: 1.2, divYield: 0.03, liquidity: 400000 },
        { id: 'AXP', name: 'American Express', sector: 'finance', bizModel: 'payment', basePrice: 7000, beta: 1.1, divYield: 0.01, liquidity: 200000 },
        { id: 'BX', name: 'Blackstone (黑石)', sector: 'finance', bizModel: 'investment', basePrice: 3800, beta: 1.5, divYield: 0.02, liquidity: 180000 },
        { id: 'V', name: 'Visa', sector: 'finance', bizModel: 'payment', basePrice: 8500, beta: 1.0, divYield: 0.01, liquidity: 400000 },
        { id: 'MA', name: 'Mastercard', sector: 'finance', bizModel: 'payment', basePrice: 14000, beta: 1.1, divYield: 0.01, liquidity: 350000 },
        { id: 'BRK.B', name: 'Berkshire Hathaway', sector: 'finance', bizModel: 'insurance', basePrice: 12000, beta: 0.8, divYield: 0.0, liquidity: 400000 },
        { id: '2501', name: '國建', sector: 'realestate', bizModel: 'residential_dev', customProduct: '國泰一品傳統高檔預售住宅案', basePrice: 180, beta: 1.1, divYield: 0.04, liquidity: 100000 },
        { id: '2542', name: '興富發', sector: 'realestate', bizModel: 'residential_dev', customProduct: '新北重劃區巨無霸千戶造鎮預售住宅案', basePrice: 450, beta: 1.4, divYield: 0.06, liquidity: 80000 },
        { id: '5522', name: '遠雄', sector: 'realestate', bizModel: 'asset_tod', customProduct: '遠雄巨蛋體育館 BOT 特許招商商場', basePrice: 750, beta: 1.2, divYield: 0.05, liquidity: 60000 },
        { id: '2548', name: '華固', sector: 'realestate', bizModel: 'commercial_dev', customProduct: '內湖科學園區高規智慧科技廠辦項目', basePrice: 1100, beta: 1.0, divYield: 0.07, liquidity: 30000 },
        { id: '5534', name: '長虹', sector: 'realestate', bizModel: 'commercial_dev', customProduct: '南港頂級 A 級綠建築商辦大樓', basePrice: 900, beta: 1.1, divYield: 0.06, liquidity: 20000 },
        { id: '9945', name: '潤泰新', sector: 'realestate', bizModel: 'contractor', customProduct: '高難度捷運共構大樓與高科技晶圓廠營造代工', basePrice: 400, beta: 1.2, divYield: 0.04, liquidity: 120000 },
        { id: '2545', name: '皇翔', sector: 'realestate', bizModel: 'residential_dev', customProduct: '信義計畫區頂級奢華指標型預售豪宅案', basePrice: 500, beta: 1.5, divYield: 0.08, liquidity: 15000 },
        { id: '2520', name: '冠德', sector: 'realestate', bizModel: 'asset_tod', customProduct: 'Global Mall 環球購物中心捷運共構商場 TOD', basePrice: 420, beta: 1.3, divYield: 0.05, liquidity: 25000 },
        { id: '2524', name: '京城', sector: 'realestate', bizModel: 'asset_tod', customProduct: '高雄精華區美術館第一排豪宅商務收租物業', basePrice: 380, beta: 1.4, divYield: 0.0, liquidity: 10000 },
        { id: '2547', name: '日勝生', sector: 'realestate', bizModel: 'asset_tod', customProduct: '捷運美河市大型 TOD 特許開發共構住宅與商場', basePrice: 120, beta: 1.6, divYield: 0.02, liquidity: 50000 },
        { id: '6177', name: '達麗', sector: 'realestate', bizModel: 'residential_dev', customProduct: '中南部科學園區周邊青年首購輕奢預售住宅案', basePrice: 550, beta: 1.5, divYield: 0.06, liquidity: 30000 },
        { id: '2536', name: '宏普', sector: 'realestate', bizModel: 'commercial_dev', customProduct: '市中心頂級共享綠能商辦地標建築', basePrice: 350, beta: 1.2, divYield: 0.06, liquidity: 20000 },
        { id: '5531', name: '鄉林', sector: 'realestate', bizModel: 'residential_dev', customProduct: '涵碧美學精品渡假村式低密預售別墅案', basePrice: 140, beta: 1.7, divYield: 0.0, liquidity: 40000 },
        { id: '2546', name: '根基', sector: 'realestate', bizModel: 'contractor', customProduct: '特大型國家高速公路與社會住宅公共工程承攬', basePrice: 850, beta: 0.9, divYield: 0.05, liquidity: 15000 },
        { id: '2912', name: '統一超', sector: 'retail', bizModel: 'cvs_minimart', basePrice: 2800, beta: 0.6, divYield: 0.04, liquidity: 50000 },
        { id: '5903', name: '全家', sector: 'retail', bizModel: 'cvs_minimart', basePrice: 2200, beta: 0.7, divYield: 0.03, liquidity: 20000 },
        { id: '5904', name: '寶雅', sector: 'retail', bizModel: 'specialty_home', basePrice: 5500, beta: 1.2, divYield: 0.04, liquidity: 15000 },
        { id: '2903', name: '遠百', sector: 'retail', bizModel: 'department_store', basePrice: 250, beta: 1.1, divYield: 0.05, liquidity: 80000 },
        { id: '2908', name: '特力', sector: 'retail', bizModel: 'specialty_home', basePrice: 200, beta: 0.8, divYield: 0.06, liquidity: 40000 },
        { id: '2915', name: '潤泰全', sector: 'retail', bizModel: 'hypermarket', basePrice: 650, beta: 1.3, divYield: 0.05, liquidity: 60000 },
        { id: '2916', name: '聚陽', sector: 'retail', bizModel: 'sports_apparel', basePrice: 3500, beta: 1.1, divYield: 0.04, liquidity: 30000 },
        { id: '1476', name: '儒鴻', sector: 'retail', bizModel: 'sports_apparel', basePrice: 5500, beta: 1.0, divYield: 0.03, liquidity: 20000 },
        { id: '9910', name: '豐泰', sector: 'retail', bizModel: 'sports_apparel', basePrice: 1800, beta: 0.9, divYield: 0.04, liquidity: 35000 },
        { id: 'COST', name: 'Costco (好市多)', sector: 'retail', bizModel: 'hypermarket', basePrice: 25000, beta: 0.9, divYield: 0.01, liquidity: 300000 },
        { id: 'WMT', name: 'Walmart (沃爾瑪)', sector: 'retail', bizModel: 'hypermarket', basePrice: 2000, beta: 0.6, divYield: 0.01, liquidity: 500000 },
        { id: 'TGT', name: 'Target (塔吉特)', sector: 'retail', bizModel: 'hypermarket', basePrice: 4500, beta: 1.0, divYield: 0.02, liquidity: 250000 },
        { id: 'HD', name: 'Home Depot', sector: 'retail', bizModel: 'specialty_home', basePrice: 11000, beta: 1.1, divYield: 0.02, liquidity: 200000 },
        { id: 'NKE', name: 'Nike (耐吉)', sector: 'retail', bizModel: 'sports_apparel', basePrice: 3000, beta: 1.3, divYield: 0.01, liquidity: 400000 },
        { id: 'LULU', name: 'Lululemon', sector: 'retail', bizModel: 'sports_apparel', basePrice: 12000, beta: 1.5, divYield: 0.0, liquidity: 150000 },
        { id: 'MC', name: 'LVMH', sector: 'retail', bizModel: 'luxury_brand', basePrice: 28000, beta: 1.2, divYield: 0.02, liquidity: 150000 },
        { id: 'RMS', name: 'Hermes (愛馬仕)', sector: 'retail', bizModel: 'luxury_brand', basePrice: 80000, beta: 0.9, divYield: 0.01, liquidity: 50000 },
        { id: '1216', name: '統一', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 750, beta: 0.5, divYield: 0.04, liquidity: 150000 },
        { id: '1201', name: '味全', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 200, beta: 0.9, divYield: 0.0, liquidity: 80000 },
        { id: '1215', name: '卜蜂', sector: 'food', bizModel: 'agri_commodity', basePrice: 950, beta: 0.8, divYield: 0.05, liquidity: 30000 },
        { id: '1210', name: '大成', sector: 'food', bizModel: 'agri_commodity', basePrice: 600, beta: 0.7, divYield: 0.05, liquidity: 40000 },
        { id: '1229', name: '聯華', sector: 'food', bizModel: 'agri_commodity', basePrice: 700, beta: 0.8, divYield: 0.06, liquidity: 50000 },
        { id: '1218', name: '泰山', sector: 'food', bizModel: 'b2b_ingredients', basePrice: 300, beta: 1.5, divYield: 0.02, liquidity: 60000 },
        { id: '1234', name: '黑松', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 400, beta: 0.6, divYield: 0.04, liquidity: 20000 },
        { id: '1227', name: '佳格', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 450, beta: 0.7, divYield: 0.05, liquidity: 25000 },
        { id: '1232', name: '大統益', sector: 'food', bizModel: 'agri_commodity', basePrice: 1400, beta: 0.5, divYield: 0.05, liquidity: 10000 },
        { id: '1702', name: '南僑', sector: 'food', bizModel: 'b2b_ingredients', basePrice: 500, beta: 0.8, divYield: 0.04, liquidity: 15000 },
        { id: 'KO', name: 'Coca-Cola (可口可樂)', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 1800, beta: 0.5, divYield: 0.03, liquidity: 600000 },
        { id: 'PEP', name: 'PepsiCo (百事)', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 5000, beta: 0.6, divYield: 0.03, liquidity: 400000 },
        { id: 'MCD', name: 'McDonald\'s (麥當勞)', sector: 'food', bizModel: 'qsr_dining', basePrice: 9000, beta: 0.8, divYield: 0.02, liquidity: 350000 },
        { id: 'SBUX', name: 'Starbucks (星巴克)', sector: 'food', bizModel: 'qsr_dining', basePrice: 2500, beta: 1.1, divYield: 0.02, liquidity: 400000 },
        { id: 'CMG', name: 'Chipotle', sector: 'food', bizModel: 'qsr_dining', basePrice: 85000, beta: 1.3, divYield: 0.0, liquidity: 100000 },
        { id: 'DPZ', name: 'Domino\'s Pizza', sector: 'food', bizModel: 'qsr_dining', basePrice: 12000, beta: 1.0, divYield: 0.01, liquidity: 80000 },
        { id: 'NESN', name: 'Nestle (雀巢)', sector: 'food', bizModel: 'fmcg_beverage', basePrice: 3500, beta: 0.5, divYield: 0.03, liquidity: 300000 },
        { id: '6472', name: '保瑞', sector: 'pharma', bizModel: 'cdmo', basePrice: 8500, beta: 1.8, divYield: 0.02, liquidity: 20000 },
        { id: '4174', name: '浩鼎', sector: 'pharma', bizModel: 'innovator', basePrice: 650, beta: 2.5, divYield: 0.0, liquidity: 40000 },
        { id: '6547', name: '高端疫苗', sector: 'pharma', bizModel: 'innovator', basePrice: 500, beta: 2.2, divYield: 0.0, liquidity: 60000 },
        { id: '4743', name: '合一', sector: 'pharma', bizModel: 'innovator', basePrice: 1800, beta: 2.0, divYield: 0.0, liquidity: 30000 },
        { id: '6446', name: '藥華藥', sector: 'pharma', bizModel: 'innovator', basePrice: 5500, beta: 1.7, divYield: 0.0, liquidity: 25000 },
        { id: '4147', name: '中裕', sector: 'pharma', bizModel: 'innovator', basePrice: 800, beta: 1.9, divYield: 0.0, liquidity: 35000 },
        { id: '6712', name: '長聖', sector: 'pharma', bizModel: 'innovator', basePrice: 1800, beta: 1.6, divYield: 0.03, liquidity: 15000 },
        { id: '6589', name: '台康生技', sector: 'pharma', bizModel: 'cdmo', basePrice: 1000, beta: 1.8, divYield: 0.0, liquidity: 25000 },
        { id: '1795', name: '美時', sector: 'pharma', bizModel: 'generics', basePrice: 2800, beta: 1.5, divYield: 0.01, liquidity: 30000 },
        { id: '1701', name: '中化', sector: 'pharma', bizModel: 'generics', basePrice: 250, beta: 0.8, divYield: 0.04, liquidity: 50000 },
        { id: '3176', name: '基亞', sector: 'pharma', bizModel: 'innovator', basePrice: 350, beta: 2.1, divYield: 0.0, liquidity: 45000 },
        { id: '4123', name: '晟德', sector: 'pharma', bizModel: 'generics', basePrice: 450, beta: 1.4, divYield: 0.03, liquidity: 60000 },
        { id: 'JNJ', name: 'Johnson & Johnson', sector: 'pharma', bizModel: 'medtech', basePrice: 4800, beta: 0.6, divYield: 0.03, liquidity: 500000 },
        { id: 'PFE', name: 'Pfizer (輝瑞)', sector: 'pharma', bizModel: 'innovator', basePrice: 850, beta: 0.8, divYield: 0.06, liquidity: 600000 },
        { id: 'MRK', name: 'Merck (默克)', sector: 'pharma', bizModel: 'innovator', basePrice: 4000, beta: 0.7, divYield: 0.02, liquidity: 400000 },
        { id: 'MRNA', name: 'Moderna (莫德納)', sector: 'pharma', bizModel: 'innovator', basePrice: 3500, beta: 2.2, divYield: 0.0, liquidity: 300000 },
        { id: 'AZN', name: 'AstraZeneca', sector: 'pharma', bizModel: 'innovator', basePrice: 2200, beta: 0.8, divYield: 0.02, liquidity: 350000 },
        { id: 'LLY', name: 'Eli Lilly (禮來)', sector: 'pharma', bizModel: 'innovator', basePrice: 25000, beta: 1.2, divYield: 0.01, liquidity: 300000 },
        { id: 'NVO', name: 'Novo Nordisk', sector: 'pharma', bizModel: 'innovator', basePrice: 4000, beta: 1.1, divYield: 0.01, liquidity: 350000 },
        { id: '2603', name: '長榮', sector: 'transport', bizModel: 'marine', basePrice: 1800, beta: 2.0, divYield: 0.05, liquidity: 400000 },
        { id: '2609', name: '陽明', sector: 'transport', bizModel: 'marine', basePrice: 650, beta: 2.2, divYield: 0.03, liquidity: 350000 },
        { id: '2615', name: '萬海', sector: 'transport', bizModel: 'marine', basePrice: 800, beta: 2.1, divYield: 0.04, liquidity: 200000 },
        { id: '2610', name: '華航', sector: 'transport', bizModel: 'airline', basePrice: 220, beta: 1.5, divYield: 0.02, liquidity: 500000 },
        { id: '2618', name: '長榮航', sector: 'transport', bizModel: 'airline', basePrice: 350, beta: 1.4, divYield: 0.03, liquidity: 450000 },
        { id: '2633', name: '台灣高鐵', sector: 'transport', bizModel: 'public_transit', basePrice: 300, beta: 0.6, divYield: 0.04, liquidity: 150000 },
        { id: '2622', name: '台灣虎航', sector: 'transport', bizModel: 'airline', basePrice: 500, beta: 1.6, divYield: 0.0, liquidity: 50000 },
        { id: '2646', name: '星宇航空', sector: 'transport', bizModel: 'airline', basePrice: 250, beta: 1.8, divYield: 0.0, liquidity: 200000 },
        { id: '2640', name: '大車隊', sector: 'transport', bizModel: 'public_transit', basePrice: 1200, beta: 0.7, divYield: 0.05, liquidity: 10000 },
        { id: '2606', name: '裕民', sector: 'transport', bizModel: 'marine', basePrice: 550, beta: 1.6, divYield: 0.06, liquidity: 60000 },
        { id: '2637', name: '慧洋-KY', sector: 'transport', bizModel: 'marine', basePrice: 700, beta: 1.5, divYield: 0.05, liquidity: 50000 },
        { id: '2642', name: '宅配通', sector: 'transport', bizModel: 'logistics', basePrice: 380, beta: 0.9, divYield: 0.03, liquidity: 15000 },
        { id: 'FDX', name: 'FedEx', sector: 'transport', bizModel: 'logistics', basePrice: 8500, beta: 1.2, divYield: 0.02, liquidity: 200000 },
        { id: 'UPS', name: 'UPS', sector: 'transport', bizModel: 'logistics', basePrice: 4500, beta: 1.1, divYield: 0.04, liquidity: 250000 },
        { id: 'UBER', name: 'Uber (優步)', sector: 'transport', bizModel: 'logistics', basePrice: 2200, beta: 1.8, divYield: 0.0, liquidity: 500000 },
        { id: 'BA', name: 'Boeing (波音)', sector: 'transport', bizModel: 'airline', basePrice: 5500, beta: 1.5, divYield: 0.0, liquidity: 300000 },
        { id: 'AIR', name: 'Airbus (空中巴士)', sector: 'transport', bizModel: 'airline', basePrice: 5000, beta: 1.4, divYield: 0.02, liquidity: 200000 },
        { id: 'DAL', name: 'Delta Air Lines', sector: 'transport', bizModel: 'airline', basePrice: 1400, beta: 1.4, divYield: 0.01, liquidity: 250000 },
        { id: 'UAL', name: 'United Airlines', sector: 'transport', bizModel: 'airline', basePrice: 1500, beta: 1.5, divYield: 0.0, liquidity: 200000 },
        { id: 'CSX', name: 'CSX Corp (鐵路)', sector: 'transport', bizModel: 'public_transit', basePrice: 1100, beta: 0.9, divYield: 0.01, liquidity: 150000 },
        { id: 'UNP', name: 'Union Pacific (鐵路)', sector: 'transport', bizModel: 'public_transit', basePrice: 7000, beta: 0.8, divYield: 0.02, liquidity: 180000 },
        { id: 'MAERSK', name: 'Maersk (馬士基)', sector: 'transport', bizModel: 'marine', basePrice: 42000, beta: 1.8, divYield: 0.05, liquidity: 100000 },
        { id: '1301', name: '台塑', sector: 'energy', bizModel: 'polymers_fibers', basePrice: 700, beta: 0.9, divYield: 0.05, liquidity: 150000 },
        { id: '1303', name: '南亞', sector: 'energy', bizModel: 'polymers_fibers', basePrice: 650, beta: 0.9, divYield: 0.05, liquidity: 120000 },
        { id: '1326', name: '台化', sector: 'energy', bizModel: 'polymers_fibers', basePrice: 600, beta: 1.0, divYield: 0.06, liquidity: 100000 },
        { id: '6505', name: '台塑化', sector: 'energy', bizModel: 'refinery_cracking', basePrice: 800, beta: 1.1, divYield: 0.04, liquidity: 80000 },
        { id: '1314', name: '中石化', sector: 'energy', bizModel: 'polymers_fibers', basePrice: 100, beta: 1.4, divYield: 0.0, liquidity: 300000 },
        { id: '1101', name: '台泥', sector: 'energy', bizModel: 'cement_kiln', basePrice: 350, beta: 0.8, divYield: 0.05, liquidity: 200000 },
        { id: '1102', name: '亞泥', sector: 'energy', bizModel: 'cement_kiln', basePrice: 400, beta: 0.7, divYield: 0.06, liquidity: 150000 },
        { id: '3708', name: '上緯投控', sector: 'energy', bizModel: 'wind_materials', basePrice: 1200, beta: 1.6, divYield: 0.02, liquidity: 30000 },
        { id: '9958', name: '世紀鋼', sector: 'energy', bizModel: 'wind_materials', basePrice: 2200, beta: 1.8, divYield: 0.01, liquidity: 40000 },
        { id: '6806', name: '森崴能源', sector: 'energy', bizModel: 'utility_ppa', basePrice: 1500, beta: 1.5, divYield: 0.01, liquidity: 25000 },
        { id: '2002', name: '中鋼', sector: 'energy', bizModel: 'steel_furnace', basePrice: 250, beta: 0.9, divYield: 0.05, liquidity: 800000 },
        { id: '2031', name: '大成鋼', sector: 'energy', bizModel: 'steel_furnace', basePrice: 400, beta: 1.3, divYield: 0.04, liquidity: 120000 },
        { id: '1605', name: '華新', sector: 'energy', bizModel: 'steel_furnace', basePrice: 350, beta: 1.2, divYield: 0.03, liquidity: 250000 },
        { id: '1513', name: '中興電', sector: 'energy', bizModel: 'gis_microgrid', basePrice: 1600, beta: 1.5, divYield: 0.03, liquidity: 80000 },
        { id: '1514', name: '亞力', sector: 'energy', bizModel: 'gis_microgrid', basePrice: 1100, beta: 1.6, divYield: 0.02, liquidity: 60000 },
        { id: '1519', name: '華城', sector: 'energy', bizModel: 'transformer_grid', basePrice: 8500, beta: 2.0, divYield: 0.01, liquidity: 30000 },
        { id: '1503', name: '士電', sector: 'energy', bizModel: 'transformer_grid', basePrice: 2500, beta: 1.4, divYield: 0.02, liquidity: 50000 },
        { id: '1606', name: '東元', sector: 'energy', bizModel: 'gis_microgrid', basePrice: 550, beta: 1.0, divYield: 0.04, liquidity: 150000 },
        { id: 'XOM', name: 'ExxonMobil (艾克森)', sector: 'energy', bizModel: 'refinery_cracking', basePrice: 3500, beta: 0.9, divYield: 0.04, liquidity: 500000 },
        { id: 'CVX', name: 'Chevron (雪佛龍)', sector: 'energy', bizModel: 'refinery_cracking', basePrice: 4800, beta: 0.9, divYield: 0.04, liquidity: 400000 },
        { id: 'SHEL', name: 'Shell (殼牌)', sector: 'energy', bizModel: 'refinery_cracking', basePrice: 2200, beta: 1.0, divYield: 0.05, liquidity: 350000 },
        { id: 'BP', name: 'BP (英國石油)', sector: 'energy', bizModel: 'refinery_cracking', basePrice: 1100, beta: 1.1, divYield: 0.05, liquidity: 300000 },
        { id: 'NEE', name: 'NextEra Energy', sector: 'energy', bizModel: 'utility_ppa', basePrice: 2000, beta: 0.7, divYield: 0.03, liquidity: 200000 },
        { id: 'GE', name: 'General Electric', sector: 'energy', bizModel: 'transformer_grid', basePrice: 4500, beta: 1.2, divYield: 0.01, liquidity: 350000 },
        { id: 'CAT', name: 'Caterpillar (卡特彼勒)', sector: 'energy', bizModel: 'steel_furnace', basePrice: 9500, beta: 1.3, divYield: 0.02, liquidity: 250000 }
    ],
    baseBanks: [
        { id: 'B1', name: '臺灣官辦銀行', desc: '大型權值銀行，審核嚴格但利率漂亮。', depositRate: 0.04, fdRate: 0.06, fdDays: 30, products: [{ id: 'L1', name: '不動產抵押貸款', type: 'secured', targetType: 're', margin: 0.02, maxLTV: 0.7, term: 180, desc: '需抵押房產。違約將遭法院強制查封拍賣。' }, { id: 'L2', name: '優質信用貸款', type: 'unsecured', margin: 0.06, maxNetWorthPct: 0.2, term: 90, desc: '無擔保信貸，額度看總淨資產。違約將嚴重影響信用。' }] },
        { id: 'B2', name: '民營信託銀行', desc: '提供高定存利率與動產質借。', depositRate: 0.02, fdRate: 0.09, fdDays: 90, products: [{ id: 'L3', name: '奢侈品動產質借', type: 'secured', targetType: 'luxury', margin: 0.08, maxLTV: 0.5, term: 60, desc: '需押付名錶或名車。違約流當。' }] },
        {
            id: 'B3', name: '🕳️ 萬利地下錢莊', type: 'underground', depositRate: 0, fdRate: 0, fdDays: 0, desc: '免徵信、免保人，只要你敢簽本票，我們就敢放款。',
            products: [
                {
                    id: 'L4',
                    name: '極道高利貸 (命)',
                    type: 'yakuza',
                    margin: 0.35, // 利率超高
                    term: 10,     // 期限僅 10 天
                    maxFixed: 3000000, // 無擔保最多只借 300 萬
                    desc: '極度危險。額度最高 300 萬，10 天為一期。若違約將遭到斷手斷腳並清空現金！'
                },
                {
                    id: 'L5',
                    name: '黑市不動產抵押',
                    type: 'secured',
                    targetType: 're',
                    margin: 0.20, // 利率高達 20% 以上 (遠超一般銀行的 2~3%)
                    term: 30,     // 期限僅 30 天 (一般銀行是好幾年)
                    maxLTV: 0.5,  // 嗜血條款：最高只能借房屋市值的 50% (一般銀行可以借到 70~80%)
                    desc: '不看聯徵，快速放款，最高可借房屋市值的 50%。若違約，房產將被黑道強制侵吞！'
                }
            ]
        }
    ],
    banks: [],
    realEstate: [
        { id: 'RE_01', name: '偏鄉漏水鐵皮屋', price: 1500000, rent: 8000, maint: 0.015, liquidityDays: 5, taxRate: 0.008, weekly: { hp: -1, hap: -3, str: 5 }, hazardProb: 0.08, condition: '危險' }, { id: 'R0', name: '老舊頂樓加蓋', price: 3000000, rent: 20000, maint: 0.01, liquidityDays: 2, taxRate: 0.012, weekly: { hp: 0, hap: 0, str: 0 }, hazardProb: 0.06, condition: '極差' }, { id: 'RE_03', name: '淡水河畔 迎風老屋', price: 6500000, rent: 35000, maint: 0.025, liquidityDays: 7, taxRate: 0.012, weekly: { hp: -1, hap: 2, str: -1 }, hazardProb: 0.05, condition: '欠佳' }, { id: 'RE_04', name: '萬華區 巷弄無梯公寓', price: 11000000, rent: 55000, maint: 0.02, liquidityDays: 5, taxRate: 0.012, weekly: { hp: 1, hap: 1, str: 0 }, hazardProb: 0.03, condition: '稍差' }, { id: 'R1', name: '中山區 中古套房', price: 15000000, rent: 80000, maint: 0.02, liquidityDays: 4, taxRate: 0.015, weekly: { hp: 1, hap: 2, str: -2 }, hazardProb: 0.02, condition: '普通' }, { id: 'RE_06', name: '內湖區 挑高小豪宅', price: 28000000, rent: 120000, maint: 0.02, liquidityDays: 5, taxRate: 0.015, weekly: { hp: 2, hap: 4, str: -4 }, hazardProb: 0.015, condition: '良好' }, { id: 'RE_07', name: '新板特區 高樓景觀戶', price: 42000000, rent: 180000, maint: 0.025, liquidityDays: 6, taxRate: 0.018, weekly: { hp: 2, hap: 6, str: -5 }, hazardProb: 0.01, condition: '優良' }, { id: 'RE_08', name: '大安區 靜巷都更潛力宅', price: 65000000, rent: 200000, maint: 0.03, liquidityDays: 8, taxRate: 0.015, weekly: { hp: 1, hap: 5, str: -3 }, hazardProb: 0.02, condition: '普通' }, { id: 'RE_09', name: '竹北高鐵 奢華水岸宅', price: 85000000, rent: 350000, maint: 0.025, liquidityDays: 6, taxRate: 0.02, weekly: { hp: 3, hap: 7, str: -6 }, hazardProb: 0.008, condition: '優良' }, { id: 'R2', name: '信義區 高級豪宅', price: 120000000, rent: 600000, maint: 0.03, liquidityDays: 7, taxRate: 0.02, weekly: { hp: 3, hap: 8, str: -8 }, hazardProb: 0.005, condition: '極佳' }, { id: 'RE_11', name: '天母 隱密溫泉別墅', price: 220000000, rent: 900000, maint: 0.035, liquidityDays: 12, taxRate: 0.025, weekly: { hp: 5, hap: 12, str: -12 }, hazardProb: 0.003, condition: '極佳' }, { id: 'R3', name: '陽明山 獨棟別墅', price: 350000000, rent: 1500000, maint: 0.04, liquidityDays: 14, taxRate: 0.03, weekly: { hp: 5, hap: 15, str: -15 }, hazardProb: 0.001, condition: '完美' }, { id: 'RE_13', name: '仁愛路 綠園道傳世豪邸', price: 550000000, rent: 2200000, maint: 0.035, liquidityDays: 20, taxRate: 0.035, weekly: { hp: 6, hap: 20, str: -18 }, hazardProb: 0.0005, condition: '完美' }, { id: 'RE_14', name: '信義計畫區 百坪露台戶', price: 880000000, rent: 3500000, maint: 0.04, liquidityDays: 25, taxRate: 0.04, weekly: { hp: 6, hap: 25, str: -25 }, hazardProb: 0.0001, condition: '完美' }, { id: 'RE_15', name: '東區 捷運共構商辦大樓', price: 2500000000, rent: 12000000, maint: 0.05, liquidityDays: 45, taxRate: 0.05, weekly: { hp: 1, hap: 30, str: -5 }, hazardProb: 0.005, condition: '優良' }
    ],
    luxury: [
        { id: 'L00', name: '名家手工高爾夫球具', price: 800000, comfort: 1, hapMonthly: 1, taxRate: 0.01, category: 'luxury' },
        { id: 'L0', name: '勞力士水鬼金錶', price: 1000000, comfort: 2, hapMonthly: 1, taxRate: 0.01, category: 'luxury' },
        { id: 'L06', name: '頂級古巴雪茄限量套組', price: 1500000, comfort: 2, hapMonthly: 1, taxRate: 0.01, category: 'luxury' },
        { id: 'L1', name: '愛馬仕限量柏金包', price: 3500000, comfort: 4, hapMonthly: 2, taxRate: 0.015, category: 'luxury' },
        { id: 'L01', name: '大師級紫砂壺', price: 5000000, comfort: 5, hapMonthly: 2, taxRate: 0.01, category: 'luxury' },
        { id: 'L02', name: '限量版百達翡麗', price: 8000000, comfort: 8, hapMonthly: 3, taxRate: 0.01, category: 'luxury' },
        { id: 'L07', name: '蘇富比珍藏年份紅酒', price: 12000000, comfort: 10, hapMonthly: 4, taxRate: 0.01, category: 'luxury' },
        { id: 'L_NEW1', name: '頂級純種阿拉伯馬', price: 18000000, comfort: 12, hapMonthly: 5, taxRate: 0.02, category: 'luxury' },
        { id: 'L2', name: '印象派百年名畫', price: 25000000, comfort: 15, hapMonthly: 5, taxRate: 0.01, category: 'luxury' },
        { id: 'L08', name: '皇室御用古董鋼琴', price: 35000000, comfort: 16, hapMonthly: 6, taxRate: 0.01, category: 'luxury' },
        { id: 'L03', name: '宋代汝窯茶盞', price: 45000000, comfort: 18, hapMonthly: 6, taxRate: 0.01, category: 'luxury' },
        { id: 'L_NEW2', name: '獨立島嶼私人俱樂部會籍', price: 60000000, comfort: 22, hapMonthly: 8, taxRate: 0.015, category: 'luxury' },
        { id: 'L3', name: '頂級稀有藍鑽項鍊', price: 80000000, comfort: 20, hapMonthly: 8, taxRate: 0.02, category: 'luxury' },
        { id: 'L09', name: '傳世明代青花瓷', price: 120000000, comfort: 22, hapMonthly: 9, taxRate: 0.015, category: 'luxury' },
        { id: 'L04', name: '佳士得拍賣清代龍袍', price: 150000000, comfort: 25, hapMonthly: 10, taxRate: 0.02, category: 'luxury' },
        { id: 'L05', name: '稀世粉鑽原石', price: 350000000, comfort: 40, hapMonthly: 15, taxRate: 0.02, category: 'luxury' },
        { id: 'L_NEW3', name: '文藝復興巨匠真跡', price: 800000000, comfort: 50, hapMonthly: 20, taxRate: 0.01, category: 'luxury' },
        { id: 'L_NEW4', name: '職業籃球隊經營權', price: 3000000000, comfort: 80, hapMonthly: 40, taxRate: 0.03, category: 'luxury' },

        // --- 私人載具與奢華交通 ---
        { id: 'V00', name: '國產二手代步車', price: 300000, comfort: 1, hapMonthly: 0, taxRate: 0.03, category: 'vehicle' },
        { id: 'V01', name: '進口重型機車', price: 1200000, comfort: 2, hapMonthly: 2, taxRate: 0.03, category: 'vehicle' },
        { id: 'V1', name: '進口雙門跑車', price: 8000000, comfort: 8, hapMonthly: 3, taxRate: 0.05, category: 'vehicle' },
        { id: 'V2', name: '豪華旗艦休旅車', price: 15000000, comfort: 12, hapMonthly: 4, taxRate: 0.06, category: 'vehicle' },
        { id: 'V02', name: '頂級防彈保母車', price: 25000000, comfort: 18, hapMonthly: 5, taxRate: 0.06, category: 'vehicle' },
        { id: 'V03', name: '經典古董超跑', price: 45000000, comfort: 20, hapMonthly: 8, taxRate: 0.07, category: 'vehicle' },
        { id: 'V_NEW1', name: '義大利客製化風神超跑', price: 80000000, comfort: 25, hapMonthly: 9, taxRate: 0.07, category: 'vehicle' },
        { id: 'V3', name: '私人豪華遊艇', price: 150000000, comfort: 30, hapMonthly: 10, taxRate: 0.08, category: 'vehicle' },
        { id: 'V04', name: '頂級商務直升機', price: 350000000, comfort: 40, hapMonthly: 15, taxRate: 0.08, category: 'vehicle' },
        { id: 'V_NEW2', name: '頂級海景超級遊艇', price: 500000000, comfort: 50, hapMonthly: 20, taxRate: 0.09, category: 'vehicle' },
        { id: 'V4', name: '私人商務客機', price: 850000000, comfort: 60, hapMonthly: 25, taxRate: 0.10, category: 'vehicle' },
        { id: 'V_NEW3', name: '灣流洲際私人客機', price: 2000000000, comfort: 100, hapMonthly: 50, taxRate: 0.12, category: 'vehicle' }
    ],
    newsPool: [
        // ==========================================
        // 【總經、地緣政治與天災】(影響大盤與通膨)
        // ==========================================
        { msg: "【國際】中東產油國爆發嚴重地緣衝突，國際原油價格單日狂飆！", stateChange: 'bear', inflationMod: 0.03, isBad: true, sectorEffect: { target: 'energy', mod: 0.15, duration: 5 } },
        { msg: "【國際】全球原物料與農產品價格崩盤！通膨壓力大幅緩解。", stateChange: 'bull', inflationMod: -0.02, isBad: false, sectorEffect: { target: 'food', mod: -0.05, duration: 3 } },
        { msg: "【總經】國內面臨嚴重少子化與缺工潮，企業人工成本大幅攀升！", stateChange: 'bear', inflationMod: 0.015, isBad: true },
        { msg: "【總經】政府公布亮眼GDP數據，經濟成長超乎預期，外資大量湧入！", stateChange: 'bull', inflationMod: 0.005, isBad: false },
        { msg: "【國際】美國聯準會 (Fed) 意外宣布大幅降息，全球資金派對啟動！", stateChange: 'bull', inflationMod: 0.02, isBad: false },
        { msg: "【黑天鵝】華爾街爆發史詩級崩盤，恐慌指數 VIX 創下歷史新高！", stateChange: 'bear', inflationMod: -0.01, isBad: true },
        { msg: "【黑天鵝】全球最大加密貨幣交易所驚傳倒閉！虛擬資產價值雪崩，引發金融機構流動性危機！", stateChange: 'bear', isBad: true, sectorEffect: { target: 'finance', mod: -0.20, duration: 6 } },
        { msg: "【天災】台灣外海發生強烈規模地震！竹科與南科部分機台停機受損，影響短期產能！", stateChange: 'bear', isBad: true, sectorEffect: { target: 'semi', mod: -0.15, duration: 4 } },
        { msg: "【國際】全球爆發新型高傳染性病毒，各國考慮封鎖邊境，市場極度恐慌！", stateChange: 'bear', inflationMod: 0.01, isBad: true, sectorEffect: { target: 'pharma', mod: 0.20, duration: 14 } },
        { msg: "【國際】中美貿易戰全面大升級！雙方互相祭出史上最高關稅報復，重創全球供應鏈。", stateChange: 'bear', inflationMod: 0.025, isBad: true, sectorEffect: { target: 'semi', mod: -0.12, duration: 8 } },
        { msg: "【總經】全球進入「完美通縮」狀態，物價直直落，但失業率飆升，消費動能急凍。", stateChange: 'bear', inflationMod: -0.04, isBad: true, sectorEffect: { target: 'retail', mod: -0.18, duration: 10 } },

        // ==========================================
        // 【政策與法規】(特定板塊影響)
        // ==========================================
        { msg: "【政策】台灣央行宣布實施超強力打房政策，嚴格限制貸款成數，宣告第七波信用管制。", stateChange: 'bear', inflationMod: -0.005, isBad: true, sectorEffect: { target: 'realestate', mod: -0.15, duration: 10 } },
        { msg: "【政策】政府明年起將正式徵收高額「碳費」！高耗能與石化鋼鐵產業成本面臨劇增。", stateChange: 'bear', inflationMod: 0.01, isBad: true, sectorEffect: { target: 'energy', mod: -0.12, duration: 8 } },
        { msg: "【法規】歐盟正式通過史上最嚴格的《AI 監管法案》，科技巨頭面臨巨額合規與侵權成本！", stateChange: 'flat', isBad: true, sectorEffect: { target: 'software_ai', mod: -0.10, duration: 5 } },
        { msg: "【政策】立法院三讀通過「超高齡社會補助條例」，大幅增加長照與新藥納保預算！", stateChange: 'bull', isBad: false, sectorEffect: { target: 'pharma', mod: 0.15, duration: 6 } },
        { msg: "【法規】中國宣布祭出史上最嚴格「未成年人網路遊戲禁令」，嚴限遊玩時間與課金上限！", stateChange: 'flat', isBad: true, sectorEffect: { target: 'game', mod: -0.25, duration: 7 } },
        { msg: "【政策】政府大舉釋出都更與社會住宅招標案，總金額創歷史新高，營造業大進補。", stateChange: 'bull', isBad: false, sectorEffect: { target: 'realestate', mod: 0.12, duration: 5 } },

        // ==========================================
        // 【產業大趨勢】(廣泛板塊影響)
        // ==========================================
        { msg: "【科技】革命性生成式 AI 技術橫空出世！全球軟硬體產業迎來超級典範轉移。", stateChange: 'bull', isBad: false, sectorEffect: { target: 'software_ai', mod: 0.15, duration: 15 } },
        { msg: "【科技】半導體先進製程遭遇技術瓶頸，良率不如預期，拖累整體科技業供應鏈出貨。", stateChange: 'bear', isBad: true, sectorEffect: { target: 'semi', mod: -0.10, duration: 7 } },
        { msg: "【航運】紅海爆發軍事危機！多艘商船遇襲，全球航運被迫繞道好望角，運價指數連日飆漲！", stateChange: 'flat', isBad: false, sectorEffect: { target: 'transport', mod: 0.18, duration: 10 } },
        { msg: "【航運】美東碼頭工人無預警大罷工！全球物流大打結，零售業面臨年底斷貨危機。", stateChange: 'bear', isBad: true, sectorEffect: { target: 'transport', mod: 0.12, duration: 6 } },
        { msg: "【綠能】政府宣布千億級綠能與重電基礎建設補貼計畫，電網強韌概念股狂飆！", stateChange: 'bull', isBad: false, sectorEffect: { target: 'energy', mod: 0.15, duration: 8 } },
        { msg: "【民生】爆發嚴重氣候乾旱，美洲大宗穀物欠收，國內雞蛋與肉品爆發供應危機！", stateChange: 'flat', inflationMod: 0.01, isBad: true, sectorEffect: { target: 'food', mod: -0.08, duration: 5 } },
        { msg: "【電信】國內電信三雄爆發削價競爭，推出 499 吃到飽流血專案，嚴重侵蝕獲利毛利。", stateChange: 'flat', isBad: true, sectorEffect: { target: 'telecom', mod: -0.12, duration: 7 } },
        { msg: "【電信】6G 通訊標準提早確立！全球電信商被迫展開新一輪龐大的資本支出軍備競賽。", stateChange: 'flat', isBad: false, sectorEffect: { target: 'telecom', mod: 0.08, duration: 5 } },
        { msg: "【汽車】全球推動燃油車禁售時間表提前，傳統車廠加速轉型，電動車零組件受惠。", stateChange: 'bull', isBad: false, sectorEffect: { target: 'auto', mod: 0.10, duration: 10 } },
        { msg: "【汽車】歐美大幅削減電動車購車補助！電動車買氣急凍，車廠被迫降價求售。", stateChange: 'bear', isBad: true, sectorEffect: { target: 'auto', mod: -0.15, duration: 8 } },
        { msg: "【消費】環保意識抬頭，快時尚品牌遭全球消費者集體抵制，成衣零售業面臨寒冬。", stateChange: 'flat', isBad: true, sectorEffect: { target: 'retail', mod: -0.15, duration: 6 } },
        { msg: "【消費】年末黑五購物節與雙11業績創下歷史新高！消費者展現驚人購買力。", stateChange: 'bull', isBad: false, sectorEffect: { target: 'retail', mod: 0.12, duration: 5 } },
        { msg: "【科技】比特幣突破十萬美元大關！挖礦熱潮再起，帶動電腦週邊與高階顯卡全面大缺貨！", stateChange: 'bull', isBad: false, sectorEffect: { target: 'electronics', mod: 0.18, duration: 8 } },
        { msg: "【金融】金管會大幅放寬金融業海外投資限制，壽險資金可望大量入市獲取更高利潤。", stateChange: 'bull', isBad: false, sectorEffect: { target: 'finance', mod: 0.10, duration: 5 } },
        { msg: "【金融】某中型區域銀行爆發擠兌危機！引發市場對金融體系流動性的嚴重擔憂。", stateChange: 'bear', isBad: true, sectorEffect: { target: 'finance', mod: -0.15, duration: 6 } },

        // ==========================================
        // 【個股專屬事件】(系統隨機抽股帶入 {stockName})
        // ==========================================
        // 業績與法說會
        { msg: "【法說會重訊】{stockName} 召開法說會，宣布下半年訂單滿載，大幅上修全年財測，買盤湧入！", isBad: false, targetSector: null, stockEffect: { mod: 0.20, duration: 3 } },
        { msg: "【法說會爆雷】{stockName} 坦言受到庫存去化影響，毛利率大幅衰退，震驚市場！", isBad: true, targetSector: null, stockEffect: { mod: -0.18, duration: 4 } },
        { msg: "【財報驚喜】{stockName} 公布單季 EPS 創下歷史新高，遠超華爾街分析師預期！", isBad: false, targetSector: null, stockEffect: { mod: 0.15, duration: 2 } },
        { msg: "【營收跳水】{stockName} 最新公布的月營收慘遭腰斬，法人機構大舉調降評等至「賣出」。", isBad: true, targetSector: null, stockEffect: { mod: -0.20, duration: 3 } },

        // 產品與研發
        { msg: "【新品發表】{stockName} 推出年度旗艦新產品，市場反應熱烈，預購量瞬間秒殺！", isBad: false, targetSector: 'electronics', stockEffect: { mod: 0.15, duration: 5 } },
        { msg: "【產品炎上】{stockName} 斥資重金打造的新品爆發嚴重設計瑕疵，面臨全球大規模召回退貨...", isBad: true, targetSector: 'auto', stockEffect: { mod: -0.25, duration: 4 } },
        { msg: "【遊戲快訊】{stockName} 開發數年的 3A 遊戲大作獲得全球玩家壓倒性好評，銷量霸榜！", isBad: false, targetSector: 'game', stockEffect: { mod: 0.25, duration: 7 } },
        { msg: "【研發受挫】{stockName} 寄予厚望的秘密研發專案宣告失敗，認列鉅額研發虧損。", isBad: true, targetSector: 'software_ai', stockEffect: { mod: -0.15, duration: 3 } },
        { msg: "【生技解盲】{stockName} 研發之標靶新藥第三期臨床實驗「數據達標」，順利解盲成功！", isBad: false, targetSector: 'pharma', stockEffect: { mod: 0.40, duration: 5 } },
        { msg: "【生技重挫】{stockName} 新藥解盲失敗！療效未達顯著差異，前期研發全數打水漂。", isBad: true, targetSector: 'pharma', stockEffect: { mod: -0.35, duration: 3 } },
        { msg: "【取得藥證】恭喜！{stockName} 成功取得美國 FDA 藥證，正式進軍全球最大醫療市場。", isBad: false, targetSector: 'pharma', stockEffect: { mod: 0.30, duration: 4 } },

        // 資本市場與籌碼面
        { msg: "【史詩軋空】論壇鄉民大集結！大量散戶瘋狂買進 {stockName}，做空機構慘遭斷頭軋空！", isBad: false, targetSector: null, stockEffect: { mod: 0.45, duration: 4 } }, // GME 事件
        { msg: "【大師加持】「股神」旗下基金遞交文件，披露砸下數十億美元建倉買進 {stockName}！", isBad: false, targetSector: null, stockEffect: { mod: 0.18, duration: 3 } },
        { msg: "【做空狙擊】知名做空機構發布百頁報告，指控 {stockName} 業務造假，股價瞬間閃崩！", isBad: true, targetSector: null, stockEffect: { mod: -0.30, duration: 4 } }, // Hindenburg 事件
        { msg: "【納入指數】MSCI 明晟宣布將 {stockName} 納入全球標準指數成分股，被動資金大舉進駐。", isBad: false, targetSector: null, stockEffect: { mod: 0.10, duration: 2 } },
        { msg: "【大股東倒貨】{stockName} 董監事與大股東申報大量轉讓持股，引發市場強烈倒貨疑慮。", isBad: true, targetSector: null, stockEffect: { mod: -0.12, duration: 2 } },

        // 醜聞、意外與訴訟
        { msg: "【社會焦點】檢調大動作搜索！{stockName} 爆發高層作假帳與掏空百億醜聞，震驚社會！", isBad: true, targetSector: null, stockEffect: { mod: -0.40, duration: 5 } },
        { msg: "【工安意外】{stockName} 廠區深夜發生大火，重要產線付之一炬，復工遙遙無期。", isBad: true, targetSector: null, stockEffect: { mod: -0.15, duration: 4 } },
        { msg: "【專利訴訟】{stockName} 遭國際大廠控告嚴重侵權，面臨鉅額賠償風險與產品禁售令。", isBad: true, targetSector: 'semi', stockEffect: { mod: -0.10, duration: 3 } },
        { msg: "【資安危機】{stockName} 遭駭客組織大規模攻擊，大量用戶個資外洩，面臨集體訴訟！", isBad: true, targetSector: 'software_ai', stockEffect: { mod: -0.18, duration: 4 } },
        { msg: "【人事地震】{stockName} 靈魂人物CEO無預警閃電辭職，引發內部派系動盪與市場擔憂。", isBad: true, targetSector: null, stockEffect: { mod: -0.08, duration: 2 } },

        // 傳聞與八卦 (影響較短，多為雜訊)
        { msg: "【商業併購】傳出國際私募基金有意以高溢價全面收購 {stockName}，激勵買盤湧入！", isBad: false, targetSector: null, stockEffect: { mod: 0.18, duration: 2 } },
        { msg: "【網路謠言】論壇瘋傳 {stockName} 即將面臨重大財務危機，引發散戶恐慌性拋售！(市場觀望)", isBad: true, targetSector: null, stockEffect: { mod: -0.06, duration: 1 } },
        { msg: "【公司澄清】{stockName} 嚴正駁斥昨日網路不實破產謠言，強調目前營運資金極度充沛。", isBad: false, targetSector: null, stockEffect: { mod: 0.06, duration: 1 } },
        { msg: "【市場傳聞】外資圈盛傳 {stockName} 已成功打入蘋果供應鏈？公司低調表示不予置評。", isBad: false, targetSector: 'electronics', stockEffect: { mod: 0.08, duration: 2 } },
        { msg: "【市場傳聞】匿名爆料指出 {stockName} 最大客戶即將抽單轉單，但法人認為可信度極低。", isBad: true, targetSector: 'semi', stockEffect: { mod: -0.05, duration: 1 } },
        { msg: "【馬路消息】聽說 {stockName} 內部正在準備跨世代的秘密武器？(投資人半信半疑)", isBad: false, targetSector: null, stockEffect: { mod: 0.02, duration: 0 } }
    ]
};


let ORIGINAL_DB = null;

function randomNormal() {
    let u = 0, v = 0;
    while (u === 0) u = Math.random();
    while (v === 0) v = Math.random();
    return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
}